name: essential_code_buffer
version: 2.0.0 #1.0.1
description: An advanced StringBuffer geared toward generating code, and source maps.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/essential_code_buffer
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  source_span: ^1.8.1
dev_dependencies:
  test: ^1.17.1